#include "gpio_config.h"

static const GpioConfig_t GpioConfig[] = {
        {CHANNEL_GP0, GPIO_PIN_FUNCTION_DIGITAL, GPIO_PIN_DIRECTION_OUTPUT, GPIO_PIN_PULLUP_DISABLED, GPIO_PIN_STATE_HIGH},
        {CHANNEL_GP1, GPIO_PIN_FUNCTION_DIGITAL, GPIO_PIN_DIRECTION_INPUT,  GPIO_PIN_PULLUP_DISABLED, GPIO_PIN_STATE_LOW},
        {CHANNEL_GP2, GPIO_PIN_FUNCTION_DIGITAL, GPIO_PIN_DIRECTION_OUTPUT, GPIO_PIN_PULLUP_DISABLED, GPIO_PIN_STATE_HIGH},
        {CHANNEL_GP3, GPIO_PIN_FUNCTION_DIGITAL, GPIO_PIN_DIRECTION_INPUT,  GPIO_PIN_PULLUP_DISABLED, GPIO_PIN_STATE_LOW},
        {CHANNEL_GP4, GPIO_PIN_FUNCTION_DIGITAL, GPIO_PIN_DIRECTION_OUTPUT, GPIO_PIN_PULLUP_DISABLED, GPIO_PIN_STATE_HIGH},
        {CHANNEL_GP5, GPIO_PIN_FUNCTION_DIGITAL, GPIO_PIN_DIRECTION_OUTPUT, GPIO_PIN_PULLUP_DISABLED, GPIO_PIN_STATE_HIGH}
};

const GpioConfig_t * const GpioConfigGet(void)
{
    return (const GpioConfig_t *) &GpioConfig[0];
}